"""Initialize wiki directory structure (idempotent)."""

from __future__ import annotations

from pathlib import Path

import click

SUBDIRS = ("raw/papers", "raw/manuals", "raw/pdk", "raw/benchmarks", "raw/sessions")

CLAUDE_MD_TEMPLATE = """# Wiki Schema

This directory follows the Karpathy LLM Wiki pattern.

## Directory layout

- `raw/` — immutable source documents (LLM reads only)
- `wiki/*.md` — compiled knowledge pages (LLM maintains)
- `index.md` — auto-generated index, regenerated by `wiki sync`
- `log.md` — append-only ingest history

## Page frontmatter

Every wiki page MUST have:

```yaml
---
type: architecture | flow | error | workload | decision
tags: [list, of, keywords]
confidence: high | medium | low
sources: [raw/papers/xxx.pdf, ...]
last_ingested: 2026-04-17
---
```

## Wiki-link format

Use `[[Page-Title]]` (Obsidian compatible). The file `wiki/Page-Title.md` resolves.
"""

INDEX_MD_TEMPLATE = """# Wiki Index

> This file is auto-generated by `wiki-sync`. Do not edit by hand.

(empty — run `wiki-sync` after adding pages)
"""

LOG_MD_TEMPLATE = """# Ingest Log

Append-only record of `wiki ingest` runs.
"""


def init_wiki(root: Path) -> None:
    """Create wiki directory structure if missing. Idempotent."""
    root.mkdir(parents=True, exist_ok=True)
    for sub in SUBDIRS:
        (root / sub).mkdir(parents=True, exist_ok=True)

    _ensure_file(root / "CLAUDE.md", CLAUDE_MD_TEMPLATE)
    _ensure_file(root / "index.md", INDEX_MD_TEMPLATE)
    _ensure_file(root / "log.md", LOG_MD_TEMPLATE)


def _ensure_file(path: Path, content: str) -> None:
    if not path.exists():
        path.write_text(content, encoding="utf-8")


@click.command()
@click.option("--root", type=click.Path(path_type=Path), default=Path("wiki"))
def main(root: Path) -> None:
    """CLI: initialize a wiki directory."""
    init_wiki(root)
    click.echo(f"Initialized wiki at {root}")


if __name__ == "__main__":
    main()
