"""Scan wiki/ pages and regenerate index.md grouped by type."""

from __future__ import annotations

from pathlib import Path

import click

from .frontmatter import parse_file

EXCLUDED_STEMS = {"index", "log", "CLAUDE"}
HEADER = "# Wiki Index\n\n> Auto-generated by `wiki-sync`. Do not edit by hand.\n\n"
EMPTY_MARKER = "(no pages yet — run `wiki-ingest` to add content)\n"


def sync_index(root: Path) -> None:
    """Rewrite {root}/index.md atomically based on page frontmatter."""
    pages = _collect_pages(root)
    content = _render_index(pages)
    _atomic_write(root / "index.md", content)


def _collect_pages(root: Path) -> list[dict]:
    """Return list of {name, type, tags, confidence} for every valid page."""
    entries: list[dict] = []
    for path in sorted(root.glob("*.md")):
        if path.stem in EXCLUDED_STEMS:
            continue
        fm, _body = parse_file(path)
        entries.append(
            {
                "name": path.stem,
                "type": fm.get("type", "uncategorized"),
                "tags": fm.get("tags", []) or [],
                "confidence": fm.get("confidence", "unknown"),
            }
        )
    return entries


def _render_index(pages: list[dict]) -> str:
    if not pages:
        return HEADER + EMPTY_MARKER
    grouped: dict[str, list[dict]] = {}
    for p in pages:
        grouped.setdefault(p["type"], []).append(p)
    parts = [HEADER]
    for type_name in sorted(grouped):
        parts.append(f"## {type_name}\n\n")
        for p in sorted(grouped[type_name], key=lambda x: x["name"]):
            marker = " ⚠ low-confidence" if p["confidence"] == "low" else ""
            tag_part = f" _(tags: {', '.join(p['tags'])})_" if p["tags"] else ""
            parts.append(f"- [[{p['name']}]]{marker}{tag_part}\n")
        parts.append("\n")
    return "".join(parts)


def _atomic_write(path: Path, content: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


@click.command()
@click.option("--root", type=click.Path(path_type=Path), default=Path("wiki"))
def main(root: Path) -> None:
    """CLI: regenerate index.md from wiki pages."""
    sync_index(root)
    click.echo(f"Synced index for {root}")


if __name__ == "__main__":
    main()
